[package]
name = "ksfc-lxi"
version = "0.1.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[lib]
name = "ksfc_lxi"
path = "src/lib.rs"

[[bin]]
name = "dev_test"
path = "src/main.rs"

[dependencies]
lxi = "0.1.2"
lazy_static = "1.2.0"
bitflags = "1.0"
