[package]
name = "ksfc-lxi"
version = "0.0.1"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[lib]
name = "ksfc_lxi"
path = "src/lib.rs"

[[bin]]
name = "dev_test"
path = "src/main.rs"

[dependencies]
tokio = "0.1"
